package com.jdw.justdrink.ui.theme

import android.os.Build
import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.dynamicDarkColorScheme
import androidx.compose.material3.dynamicLightColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.remember
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext

@Immutable
data class ColorFamily(
    val color: Color,
    val onColor: Color,
    val colorContainer: Color,
    val onColorContainer: Color
)

val unspecified_scheme = ColorFamily(
    Color.Unspecified, Color.Unspecified, Color.Unspecified, Color.Unspecified
)

sealed class AppTheme(
    val name: String,
    val lightScheme: androidx.compose.material3.ColorScheme,
    val darkScheme: androidx.compose.material3.ColorScheme
) {
    object Default : AppTheme(
        "Default",
        lightScheme = lightColorScheme(
            primary = Color(0xFF904A46),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFFFDAD7),
            onPrimaryContainer = Color(0xFF733330),
            secondary = Color(0xFF775654),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFFFDAD7),
            onSecondaryContainer = Color(0xFF5D3F3D),
            tertiary = Color(0xFF725B2E),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFFFDEA6),
            onTertiaryContainer = Color(0xFF594419),
            error = Color(0xFFBA1A1A),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFFFFDAD6),
            onErrorContainer = Color(0xFF93000A),
            background = Color(0xFFFFF8F7),
            onBackground = Color(0xFF231919),
            surface = Color(0xFFFFF8F7),
            onSurface = Color(0xFF231919),
            surfaceVariant = Color(0xFFF5DDDB),
            onSurfaceVariant = Color(0xFF534342),
            outline = Color(0xFF857371),
            outlineVariant = Color(0xFFD8C2BF),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFF382E2D),
            inverseOnSurface = Color(0xFFFFEDEB),
            inversePrimary = Color(0xFFFFB3AD),
            surfaceDim = Color(0xFFE8D6D4),
            surfaceBright = Color(0xFFFFF8F7),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFFFF0EF),
            surfaceContainer = Color(0xFFFCEAE8),
            surfaceContainerHigh = Color(0xFFF6E4E2),
            surfaceContainerHighest = Color(0xFFF1DEDD)
        ),
        darkScheme = darkColorScheme(
            primary = Color(0xFFFFB3AD),
            onPrimary = Color(0xFF571E1B),
            primaryContainer = Color(0xFF733330),
            onPrimaryContainer = Color(0xFFFFDAD7),
            secondary = Color(0xFFE7BDB9),
            onSecondary = Color(0xFF442927),
            secondaryContainer = Color(0xFF5D3F3D),
            onSecondaryContainer = Color(0xFFFFDAD7),
            tertiary = Color(0xFFE1C28C),
            onTertiary = Color(0xFF402D04),
            tertiaryContainer = Color(0xFF594419),
            onTertiaryContainer = Color(0xFFFFDEA6),
            error = Color(0xFFFFB4AB),
            onError = Color(0xFF690005),
            errorContainer = Color(0xFF93000A),
            onErrorContainer = Color(0xFFFFDAD6),
            background = Color(0xFF1A1110),
            onBackground = Color(0xFFF1DEDD),
            surface = Color(0xFF1A1110),
            onSurface = Color(0xFFF1DEDD),
            surfaceVariant = Color(0xFF534342),
            onSurfaceVariant = Color(0xFFD8C2BF),
            outline = Color(0xFFA08C8A),
            outlineVariant = Color(0xFF534342),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFFF1DEDD),
            inverseOnSurface = Color(0xFF382E2D),
            inversePrimary = Color(0xFF904A46),
            surfaceDim = Color(0xFF1A1110),
            surfaceBright = Color(0xFF423736),
            surfaceContainerLowest = Color(0xFF140C0B),
            surfaceContainerLow = Color(0xFF231919),
            surfaceContainer = Color(0xFF271D1C),
            surfaceContainerHigh = Color(0xFF322827),
            surfaceContainerHighest = Color(0xFF3D3231)
        )
    )

    object Strawberry : AppTheme(
        "Strawberry",
        lightScheme = lightColorScheme(
            primary = Color(0xFF9F1414),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFFFDAD4),
            onPrimaryContainer = Color(0xFF330303),
            secondary = Color(0xFF775654),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFFFDAD4),
            onSecondaryContainer = Color(0xFF2C1513),
            tertiary = Color(0xFF725B2E),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFFFDEA6),
            onTertiaryContainer = Color(0xFF261900),
            error = Color(0xFFBA1A1A),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFFFFDAD6),
            onErrorContainer = Color(0xFF410002),
            background = Color(0xFFFFF8F7),
            onBackground = Color(0xFF231919),
            surface = Color(0xFFFFF8F7),
            onSurface = Color(0xFF231919),
            surfaceVariant = Color(0xFFF5DDDB),
            onSurfaceVariant = Color(0xFF534342),
            outline = Color(0xFF857371),
            outlineVariant = Color(0xFFD8C2BF),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFF382E2D),
            inverseOnSurface = Color(0xFFFFEDEB),
            inversePrimary = Color(0xFFFFB3A8),
            surfaceDim = Color(0xFFE8D6D4),
            surfaceBright = Color(0xFFFFF8F7),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFFFF0EF),
            surfaceContainer = Color(0xFFFCEAE8),
            surfaceContainerHigh = Color(0xFFF6E4E2),
            surfaceContainerHighest = Color(0xFFF1DEDD)
        ),
        darkScheme = darkColorScheme(
            primary = Color(0xFFE14E4E),
            onPrimary = Color(0xFF5C0A0A),
            primaryContainer = Color(0xFF9F1414),
            onPrimaryContainer = Color(0xFFFFDAD4),
            secondary = Color(0xFFE7BDB9),
            onSecondary = Color(0xFF442927),
            secondaryContainer = Color(0xFF5D3F3D),
            onSecondaryContainer = Color(0xFFFFDAD4),
            tertiary = Color(0xFFE1C28C),
            onTertiary = Color(0xFF402D04),
            tertiaryContainer = Color(0xFF594419),
            onTertiaryContainer = Color(0xFFFFDEA6),
            error = Color(0xFFFFB4AB),
            onError = Color(0xFF690005),
            errorContainer = Color(0xFF93000A),
            onErrorContainer = Color(0xFFFFDAD6),
            background = Color(0xFF1A1716),
            onBackground = Color(0xFFF1DEDD),
            surface = Color(0xFF1A1716),
            onSurface = Color(0xFFF1DEDD),
            surfaceVariant = Color(0xFF534342),
            onSurfaceVariant = Color(0xFFD8C2BF),
            outline = Color(0xFFA08C8A),
            outlineVariant = Color(0xFF534342),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFFF1DEDD),
            inverseOnSurface = Color(0xFF382E2D),
            inversePrimary = Color(0xFF9F1414),
            surfaceDim = Color(0xFF1A1716),
            surfaceBright = Color(0xFF423736),
            surfaceContainerLowest = Color(0xFF140C0B),
            surfaceContainerLow = Color(0xFF231919),
            surfaceContainer = Color(0xFF271D1C),
            surfaceContainerHigh = Color(0xFF322827),
            surfaceContainerHighest = Color(0xFF3D3231)
        )
    )

    object Lime : AppTheme(
        "Lime",
        lightScheme = lightColorScheme(
            primary = Color(0xFF09933C),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFF95F990),
            onPrimaryContainer = Color(0xFF043314),
            secondary = Color(0xFF4AF88A),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFCBFFE0),
            onSecondaryContainer = Color(0xFF043314),
            tertiary = Color(0xFF386A1E),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFB9F397),
            onTertiaryContainer = Color(0xFF082100),
            error = Color(0xFFBA1A1A),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFFFFDAD6),
            onErrorContainer = Color(0xFF410002),
            background = Color(0xFFFCFDF7),
            onBackground = Color(0xFF1A1C19),
            surface = Color(0xFFFCFDF7),
            onSurface = Color(0xFF1A1C19),
            surfaceVariant = Color(0xFFDEE5D9),
            onSurfaceVariant = Color(0xFF424940),
            outline = Color(0xFF72796F),
            outlineVariant = Color(0xFFC2C9BD),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFF2F312D),
            inverseOnSurface = Color(0xFFF0F1EB),
            inversePrimary = Color(0xFF7ADC77),
            surfaceDim = Color(0xFFDCDDD7),
            surfaceBright = Color(0xFFFCFDF7),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFF6F7F1),
            surfaceContainer = Color(0xFFF0F2EC),
            surfaceContainerHigh = Color(0xFFEBECE6),
            surfaceContainerHighest = Color(0xFFE5E6E0)
        ),
        darkScheme = darkColorScheme(
            primary = Color(0xFF7CF7A5),
            onPrimary = Color(0xFF003914),
            primaryContainer = Color(0xFF00521F),
            onPrimaryContainer = Color(0xFF95F990),
            secondary = Color(0xFF4AF88A),
            onSecondary = Color(0xFF003914),
            secondaryContainer = Color(0xFF00521F),
            onSecondaryContainer = Color(0xFF95F990),
            tertiary = Color(0xFF9ED67E),
            onTertiary = Color(0xFF133800),
            tertiaryContainer = Color(0xFF225107),
            onTertiaryContainer = Color(0xFFB9F397),
            error = Color(0xFFFFB4AB),
            onError = Color(0xFF690005),
            errorContainer = Color(0xFF93000A),
            onErrorContainer = Color(0xFFFFDAD6),
            background = Color(0xFF202125),
            onBackground = Color(0xFFE2E3DD),
            surface = Color(0xFF202125),
            onSurface = Color(0xFFE2E3DD),
            surfaceVariant = Color(0xFF424940),
            onSurfaceVariant = Color(0xFFC2C9BD),
            outline = Color(0xFF8C9388),
            outlineVariant = Color(0xFF424940),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFFE2E3DD),
            inverseOnSurface = Color(0xFF2F312D),
            inversePrimary = Color(0xFF006D2A),
            surfaceDim = Color(0xFF202125),
            surfaceBright = Color(0xFF464946),
            surfaceContainerLowest = Color(0xFF1B1B1E),
            surfaceContainerLow = Color(0xFF282A28),
            surfaceContainer = Color(0xFF2C2E2C),
            surfaceContainerHigh = Color(0xFF373936),
            surfaceContainerHighest = Color(0xFF424441)
        )
    )

    object Tako : AppTheme(
        "Tako",
        lightScheme = lightColorScheme(
            primary = Color(0xFFA85D14),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFFFDCC6),
            onPrimaryContainer = Color(0xFF3C2004),
            secondary = Color(0xFFF3B375),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFFFDCC6),
            onSecondaryContainer = Color(0xFF2D1600),
            tertiary = Color(0xFF6F5C40),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFF9DFBB),
            onTertiaryContainer = Color(0xFF261900),
            error = Color(0xFFBA1A1A),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFFFFDAD6),
            onErrorContainer = Color(0xFF410002),
            background = Color(0xFFFFFBFF),
            onBackground = Color(0xFF201B16),
            surface = Color(0xFFFFFBFF),
            onSurface = Color(0xFF201B16),
            surfaceVariant = Color(0xFFF4DED2),
            onSurfaceVariant = Color(0xFF52443A),
            outline = Color(0xFF847469),
            outlineVariant = Color(0xFFD7C2B7),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFF352F2A),
            inverseOnSurface = Color(0xFFFAEFE8),
            inversePrimary = Color(0xFFFFB77E),
            surfaceDim = Color(0xFFE8D7CE),
            surfaceBright = Color(0xFFFFFBFF),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFFFF5EE),
            surfaceContainer = Color(0xFFFCEFE7),
            surfaceContainerHigh = Color(0xFFF6E9E1),
            surfaceContainerHighest = Color(0xFFF0E3DC)
        ),
        darkScheme = darkColorScheme(
            primary = Color(0xFFFCCD9F),
            onPrimary = Color(0xFF5B3000),
            primaryContainer = Color(0xFFA85D14),
            onPrimaryContainer = Color(0xFFFFDCC6),
            secondary = Color(0xFFF3B375),
            onSecondary = Color(0xFF4B2800),
            secondaryContainer = Color(0xFF6A3D0A),
            onSecondaryContainer = Color(0xFFFFDCC6),
            tertiary = Color(0xFFDCC3A0),
            onTertiary = Color(0xFF3D2E16),
            tertiaryContainer = Color(0xFF55442A),
            onTertiaryContainer = Color(0xFFF9DFBB),
            error = Color(0xFFFFB4AB),
            onError = Color(0xFF690005),
            errorContainer = Color(0xFF93000A),
            onErrorContainer = Color(0xFFFFDAD6),
            background = Color(0xFF21212E),
            onBackground = Color(0xFFECE0D9),
            surface = Color(0xFF21212E),
            onSurface = Color(0xFFECE0D9),
            surfaceVariant = Color(0xFF52443A),
            onSurfaceVariant = Color(0xFFD7C2B7),
            outline = Color(0xFF9F8D82),
            outlineVariant = Color(0xFF52443A),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFFECE0D9),
            inverseOnSurface = Color(0xFF352F2A),
            inversePrimary = Color(0xFFA85D14),
            surfaceDim = Color(0xFF21212E),
            surfaceBright = Color(0xFF494642),
            surfaceContainerLowest = Color(0xFF1C1C28),
            surfaceContainerLow = Color(0xFF2A2A3C),
            surfaceContainer = Color(0xFF2E2E40),
            surfaceContainerHigh = Color(0xFF39394B),
            surfaceContainerHighest = Color(0xFF444456)
        )
    )

    object DuskDawn : AppTheme(
        "Dusk Dawn",
        lightScheme = lightColorScheme(
            primary = Color(0xFF8D0C3F),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFFFD9E1),
            onPrimaryContainer = Color(0xFF370318),
            secondary = Color(0xFFF02475),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFFFD9E1),
            onSecondaryContainer = Color(0xFF3B0018),
            tertiary = Color(0xFF7D5800),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFFFDEA0),
            onTertiaryContainer = Color(0xFF271900),
            error = Color(0xFFBA1A1A),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFFFFDAD6),
            onErrorContainer = Color(0xFF410002),
            background = Color(0xFFFFFBFF),
            onBackground = Color(0xFF201A1C),
            surface = Color(0xFFFFFBFF),
            onSurface = Color(0xFF201A1C),
            surfaceVariant = Color(0xFFF2DEE2),
            onSurfaceVariant = Color(0xFF514347),
            outline = Color(0xFF837377),
            outlineVariant = Color(0xFFD5C2C6),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFF352F30),
            inverseOnSurface = Color(0xFFFAEDEF),
            inversePrimary = Color(0xFFFFB1C6),
            surfaceDim = Color(0xFFE8D6D9),
            surfaceBright = Color(0xFFFFFBFF),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFFFF0F3),
            surfaceContainer = Color(0xFFFCE9ED),
            surfaceContainerHigh = Color(0xFFF6E3E7),
            surfaceContainerHighest = Color(0xFFF0DDE1)
        ),
        darkScheme = darkColorScheme(
            primary = Color(0xFFE570A0),
            onPrimary = Color(0xFF550D2D),
            primaryContainer = Color(0xFF8D0C3F),
            onPrimaryContainer = Color(0xFFFFD9E1),
            secondary = Color(0xFFF02475),
            onSecondary = Color(0xFF5D1135),
            secondaryContainer = Color(0xFF7D1A4A),
            onSecondaryContainer = Color(0xFFFFD9E1),
            tertiary = Color(0xFFF8BC48),
            onTertiary = Color(0xFF422C00),
            tertiaryContainer = Color(0xFF5F4100),
            onTertiaryContainer = Color(0xFFFFDEA0),
            error = Color(0xFFFFB4AB),
            onError = Color(0xFF690005),
            errorContainer = Color(0xFF93000A),
            onErrorContainer = Color(0xFFFFDAD6),
            background = Color(0xFF16151D),
            onBackground = Color(0xFFECE0E2),
            surface = Color(0xFF16151D),
            onSurface = Color(0xFFECE0E2),
            surfaceVariant = Color(0xFF514347),
            onSurfaceVariant = Color(0xFFD5C2C6),
            outline = Color(0xFF9E8C90),
            outlineVariant = Color(0xFF514347),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFFECE0E2),
            inverseOnSurface = Color(0xFF352F30),
            inversePrimary = Color(0xFF8D0C3F),
            surfaceDim = Color(0xFF16151D),
            surfaceBright = Color(0xFF3E3839),
            surfaceContainerLowest = Color(0xFF110F17),
            surfaceContainerLow = Color(0xFF272026),
            surfaceContainer = Color(0xFF2B242A),
            surfaceContainerHigh = Color(0xFF362F34),
            surfaceContainerHighest = Color(0xFF41393F)
        )
    )

    object TealSapphire : AppTheme(
        "Teal Sapphire",
        lightScheme = lightColorScheme(
            primary = Color(0xFF1D698B),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFB5EBFF),
            onPrimaryContainer = Color(0xFF02212C),
            secondary = Color(0xFF589AB8),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFB5EBFF),
            onSecondaryContainer = Color(0xFF02212C),
            tertiary = Color(0xFF006D2A),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFF95F990),
            onTertiaryContainer = Color(0xFF002107),
            error = Color(0xFFBA1A1A),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFFFFDAD6),
            onErrorContainer = Color(0xFF410002),
            background = Color(0xFFFCFCFF),
            onBackground = Color(0xFF191C1E),
            surface = Color(0xFFFCFCFF),
            onSurface = Color(0xFF191C1E),
            surfaceVariant = Color(0xFFDCE4E9),
            onSurfaceVariant = Color(0xFF40484C),
            outline = Color(0xFF70787D),
            outlineVariant = Color(0xFFC0C8CD),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFF2E3133),
            inverseOnSurface = Color(0xFFEFF1F3),
            inversePrimary = Color(0xFF80B8D1),
            surfaceDim = Color(0xFFDBDCDE),
            surfaceBright = Color(0xFFFCFCFF),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFF6F6F9),
            surfaceContainer = Color(0xFFF0F1F3),
            surfaceContainerHigh = Color(0xFFEAEBED),
            surfaceContainerHighest = Color(0xFFE4E5E7)
        ),
        darkScheme = darkColorScheme(
            primary = Color(0xFF80B8D1),
            onPrimary = Color(0xFF003749),
            primaryContainer = Color(0xFF1D698B),
            onPrimaryContainer = Color(0xFFB5EBFF),
            secondary = Color(0xFF589AB8),
            onSecondary = Color(0xFF003749),
            secondaryContainer = Color(0xFF1D698B),
            onSecondaryContainer = Color(0xFFB5EBFF),
            tertiary = Color(0xFF7ADC77),
            onTertiary = Color(0xFF00390C),
            tertiaryContainer = Color(0xFF005316),
            onTertiaryContainer = Color(0xFF95F990),
            error = Color(0xFFFFB4AB),
            onError = Color(0xFF690005),
            errorContainer = Color(0xFF93000A),
            onErrorContainer = Color(0xFFFFDAD6),
            background = Color(0xFF14191B),
            onBackground = Color(0xFFE1E3E5),
            surface = Color(0xFF14191B),
            onSurface = Color(0xFFE1E3E5),
            surfaceVariant = Color(0xFF40484C),
            onSurfaceVariant = Color(0xFFC0C8CD),
            outline = Color(0xFF8A9297),
            outlineVariant = Color(0xFF40484C),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFFE1E3E5),
            inverseOnSurface = Color(0xFF2E3133),
            inversePrimary = Color(0xFF1D698B),
            surfaceDim = Color(0xFF14191B),
            surfaceBright = Color(0xFF3A3F41),
            surfaceContainerLowest = Color(0xFF0F1416),
            surfaceContainerLow = Color(0xFF1D2528),
            surfaceContainer = Color(0xFF21292C),
            surfaceContainerHigh = Color(0xFF2C3437),
            surfaceContainerHighest = Color(0xFF373F42)
        )
    )

    object YinYang : AppTheme(
        "Yin Yang",
        lightScheme = lightColorScheme(
            primary = Color(0xFF000000),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFDCDCDC),
            onPrimaryContainer = Color(0xFF191919),
            secondary = Color(0xFFFFFFFF),
            onSecondary = Color(0xFF000000),
            secondaryContainer = Color(0xFFFFFFFF),
            onSecondaryContainer = Color(0xFF191919),
            tertiary = Color(0xFF7A7A7A),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFDCDCDC),
            onTertiaryContainer = Color(0xFF191919),
            error = Color(0xFFBA1A1A),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFFFFDAD6),
            onErrorContainer = Color(0xFF410002),
            background = Color(0xFFFCFCFC),
            onBackground = Color(0xFF1A1A1A),
            surface = Color(0xFFFCFCFC),
            onSurface = Color(0xFF1A1A1A),
            surfaceVariant = Color(0xFFE0E0E0),
            onSurfaceVariant = Color(0xFF444444),
            outline = Color(0xFF747474),
            outlineVariant = Color(0xFFC4C4C4),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFF2F2F2F),
            inverseOnSurface = Color(0xFFF1F1F1),
            inversePrimary = Color(0xFFB8B8B8),
            surfaceDim = Color(0xFFDCDCDC),
            surfaceBright = Color(0xFFFCFCFC),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFF6F6F6),
            surfaceContainer = Color(0xFFF0F0F0),
            surfaceContainerHigh = Color(0xFFEAEAEA),
            surfaceContainerHighest = Color(0xFFE4E4E4)
        ),
        darkScheme = darkColorScheme(
            primary = Color(0xFFDCDCDC),
            onPrimary = Color(0xFF2E2E2E),
            primaryContainer = Color(0xFF444444),
            onPrimaryContainer = Color(0xFFDCDCDC),
            secondary = Color(0xFFFFFFFF),
            onSecondary = Color(0xFF2E2E2E),
            secondaryContainer = Color(0xFF444444),
            onSecondaryContainer = Color(0xFFFFFFFF),
            tertiary = Color(0xFFB8B8B8),
            onTertiary = Color(0xFF363636),
            tertiaryContainer = Color(0xFF4E4E4E),
            onTertiaryContainer = Color(0xFFDCDCDC),
            error = Color(0xFFFFB4AB),
            onError = Color(0xFF690005),
            errorContainer = Color(0xFF93000A),
            onErrorContainer = Color(0xFFFFDAD6),
            background = Color(0xFF1A1A1A),
            onBackground = Color(0xFFE4E4E4),
            surface = Color(0xFF1A1A1A),
            onSurface = Color(0xFFE4E4E4),
            surfaceVariant = Color(0xFF444444),
            onSurfaceVariant = Color(0xFFC4C4C4),
            outline = Color(0xFF8E8E8E),
            outlineVariant = Color(0xFF444444),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFFE4E4E4),
            inverseOnSurface = Color(0xFF2F2F2F),
            inversePrimary = Color(0xFF5C5C5C),
            surfaceDim = Color(0xFF1A1A1A),
            surfaceBright = Color(0xFF424242),
            surfaceContainerLowest = Color(0xFF141414),
            surfaceContainerLow = Color(0xFF2C2C2C),
            surfaceContainer = Color(0xFF303030),
            surfaceContainerHigh = Color(0xFF3B3B3B),
            surfaceContainerHighest = Color(0xFF464646)
        )
    )
}

val themes = listOf(
    AppTheme.Default,
    AppTheme.Strawberry,
    AppTheme.Lime,
    AppTheme.Tako,
    AppTheme.DuskDawn,
    AppTheme.TealSapphire,
    AppTheme.YinYang
)

@Composable
fun AppTheme(
    darkTheme: Boolean = isSystemInDarkTheme(),
    dynamicColor: Boolean = true,
    selectedTheme: AppTheme = AppTheme.Default,
    content: @Composable () -> Unit
) {
    val context = LocalContext.current
    val colorScheme = remember(selectedTheme, darkTheme, dynamicColor) {
        when {
            dynamicColor && Build.VERSION.SDK_INT >= Build.VERSION_CODES.S -> {
                if (darkTheme) dynamicDarkColorScheme(context) else dynamicLightColorScheme(context)
            }
            darkTheme -> selectedTheme.darkScheme
            else -> selectedTheme.lightScheme
        }
    }

    MaterialTheme(
        colorScheme = colorScheme,
        content = content
    )
}